### ISSUE TITLE
inconsistent metric names

### ISSUE THREAD

**Issue by pfliu-nlp** [ExpressAI/EaaS_API_dev#27]
`rouge2` (in class definition) <->  `rouge_2` (in sample-level output json)

**Comment by pfliu-nlp** [comment]
similar case on `bert_score`

**Comment by yyy-Apple** [comment]
> 
Does this mean we should have `bert_score_p`, `bert_score_r`, `bert_score_f` as separate metrics?

**Comment by pfliu-nlp** [comment]
Thanks for fixing these issues.
